name: Build Nginx Orchestrator

on:
  workflow_dispatch:
    inputs:
      nginx_version:
        description: "Specify the nginx version"
        required: true
        default: "1.28.0"
      openssl_version:
        description: "Specify the openssl version"
        required: true
        default: "openssl-3.5.0"
      prefix:
        description: "Specify the installation prefix"
        required: true
        default: "/usr/local/nginx"

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
      # 1. 触发基础镜像构建
      - name: Trigger Docker Image Build
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-docker-environment-image.yml',
              ref: 'main',
              inputs: {}
            })
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      # 2. 触发扩展包编译
      - name: Trigger Expand Build
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-nginx-expand.yml',
              ref: 'main',
              inputs: {
                openssl_version: '${{ github.event.inputs.openssl_version }}'
              }
            })
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      # 3. 等待依赖工作流完成
      - name: Wait for dependencies
        uses: fountainhead/action-wait-for-check@v1.2.0
        with:
          token: ${{ secrets.PAT }}
          checkName: 'Build Docker Environment Image'
          ref: 'main'
          timeoutSeconds: 3600
